### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by Twig6943**

### CODE REVIEW

**Comment by Twig6943** [comment]
Also @LuisMayo please for the love of god upload binaries :sob:

**Review by LuisMayo — APPROVED** [review]

**Comment by LuisMayo** [comment]
I really should shouldn't I :(

**Comment by Twig6943** [comment]
yes, please (I cant build myself cuz skill issue)

**Comment by LuisMayo** [comment]
Ok so the reason you couldn't buy it it's because dependencies were broken.

I've fixed them now, I'm still trying to produce the binaries

**Comment by Twig6943** [comment]
Thanks a lot. Looking forward to the binaries. Could you package the linux binaries as .AppImage if possible? (Just binaries are also appreciated)

**Comment by Twig6943** [comment]
still waiting for binaries

**Pull request closed without merging**
